version: 'build-{build}-{branch}'

platform: x64

build:
  parallel: true

cache:
  - c:\msys64\var\cache\pacman\pkg -> .ci\install.bat

image:
  - Visual Studio 2017

environment:
  # Create expected SHELL variable for pipenv.
  SHELL: 'windows'
  CTEST_OUTPUT_ON_FAILURE: '1'
  matrix:
    - CMAKE_GENERATOR: 'Visual Studio 15 2017 Win64'
      BUILDFLAGS: '/verbosity:normal'
      TESTTARGET: 'RUN_TESTS'
      CXXFLAGS: ''
      CMAKEARGS: '-DBOOST_ROOT="C:\Libraries\boost_1_67_0"'
    - CMAKE_GENERATOR: 'MSYS Makefiles'
      BUILDFLAGS: 'VERBOSE=1'
      TESTTARGET: 'test'
      CXXFLAGS: ''
      CMAKEARGS: ''

matrix:
  fast_finish: true

init:
  - set PATH=C:\msys64\MINGW64\bin;C:\msys64\usr\bin;%PATH%
  - set PATH=C:\Python37-x64;C:\Python37-x64\Scripts;%PATH%
  # Remove Python 2.7 from path
  - set PATH=%PATH:C:\Python27;=%
  - set PATH=%PATH:C:\Python27\Scripts;=%

install:
  - python -m pip install pipenv
  - '%APPVEYOR_BUILD_FOLDER%\.ci\install.bat'
  - pipenv install --three

before_build:
  - pipenv run python --version
  - cmake --version

build_script:
  - pipenv run python setup --generator="%CMAKE_GENERATOR%" --prefix="C:\Software\getkw" --cmake-options="%CMAKEARGS%"
  - pipenv run cmake --build build --config Debug -- "%BUILDFLAGS%"
  - pipenv run cmake --build build --target install --config Debug
  - pipenv run cmake --build build --target "%TESTTARGET%" --config Debug

deploy: off
