# See http://msdn.microsoft.com/en-us/library/ms164311.aspx for
# command-line options to MSBuild.

# Speeding up a Visual Studio build.
# http://blogs.msdn.com/b/vcblog/archive/2011/01/05/damn-my-vc-project-is-building-slower-in-vs2010-what-do-i-do-now-a-step-by-step-guide.aspx
version: 'build-{build}-{branch}'

platform: x86

build:
  parallel: true

environment:
  # Create expected SHELL variable for pipenv.
  SHELL: "windows"
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      MSYSTEM: MINGW64
      GENERATOR: "MSYS Makefiles"

matrix:
  fast_finish: true

init:
  - set PATH=C:\msys64\%MSYSTEM%\bin;C:\msys64\usr\bin;%PATH%

cache:
  - c:\msys64\var\cache\pacman\pkg
  - c:\tools\vcpkg\installed\

install:
  - pacman -S --needed --noconfirm pacman-mirrors
  - pacman -Syuu --needed --noconfirm --ask=127
  - pacman -S --noconfirm mingw64/mingw-w64-x86_64-boost
  - python -m pip install pipenv
  - pipenv install

before_build:
  - cmake --version
  - pipenv --version

build_script:
  - pipenv run python setup --cxx=g++ --generator="%GENERATOR%" --prefix="C:\Software\getkw"
  - cd build
  - cmake --build . --target install
  - ctest --parallel 2 --output-on-failure --verbose

deploy: off
